FROM quarkus-semeru-authservice-step1

COPY startQuarkus.sh /app/
RUN chmod +x startQuarkus.sh
RUN ./startQuarkus.sh

RUN chown -R 1001 /app/cr
RUN chown -R 1001 /app/out
RUN chown -R 1001 /app/err

CMD ["bash", "startQuarkus.sh"]
